### ISSUE TITLE
Connection Refused of Backend Server results in complete homebridge crash

### ISSUE THREAD

**Issue by EdJoPaTo** [lucacri/homebridge-http-temperature-humidity#16]
Error: connect ECONNREFUSED 127.0.0.1:3000
    at doRequest (/usr/local/lib/node_modules/homebridge-httptemperaturehumidity/node_modules/sync-request/index.js:31:11)
    at Object.HttpTemphum.getState (/usr/local/lib/node_modules/homebridge-httptemperaturehumidity/index.js:51:12)

accessory could just set "not available" instead of full crash

**Comment by paulobriennz** [comment]
any luck on this?  I have this same issue, really annoying, if one of my temp units goes off line, homebridge crashes completely.. any change we could make to not completely crash? ive had a play around but I'm not that good with js

**Comment by roozbehf** [comment]
I fixed this in this commit: 8b5c97a0bb9d36a92be431515e7d20fb43f6e41a on my forked repo. 

Waiting to be merged into this repository. :-)

**Comment by jendaz** [comment]
Same issue. Could you merge this fix to production?

**Comment by EdJoPaTo** [comment]
@jendaz: See #32 ;)

Looks like @lucacri is just not willing to accept this 🤔

**Comment by jendaz** [comment]
But it looks like that maybe it is fixed in last merge #29 because it is switched to different http library.
