### ISSUE TITLE
Homebridge crashes if not reacheble (eg. not connected the luaMCU)

### ISSUE THREAD

**Issue by neonightmare** [lucacri/homebridge-http-temperature-humidity#19]
Hi,
got this message after starting homebridge with deconnected LUA/MCU.

`/usr/local/lib/node_modules/homebridge-httptemperaturehumidity/node_modules/sync-request/index.js:31
    throw new Error(response.error.message || response.error || response);
    ^

Error: connect EHOSTUNREACH 192.168.1.119:80
    at doRequest (/usr/local/lib/node_modules/homebridge-httptemperaturehumidity/node_modules/sync-request/index.js:31:11)
    at Object.HttpTemphum.getState (/usr/local/lib/node_modules/homebridge-httptemperaturehumidity/index.js:51:12)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:587:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:554:8)
    at emitThree (events.js:110:13)
    at HAPServer.emit (events.js:188:7)
pi@raspberrypi ~/.homebridge $ `

any idea?

thx neo

**Comment by lucacri** [comment]
Sorry, really no idea. Anyone else experiencing the same problem?

**Comment by paulobriennz** [comment]
I get same problem on a timeout.  Anything we could do to stop a fatal crash at line 31 of sync-requests/index.js?  I tried to have a play around but didn't get anywhere.  If it could just log error but not crash completely..

\npm\node_modules\homebridge-http-temperature\node_modules\sync-request\index.js:31
    throw new Error(response.error.message || response.error || response);
    ^

Error: connect ETIMEDOUT 192.168.1.123:80
    at doRequest (C:\Users\paul.obrien\AppData\Roaming\npm\node_modules\homebridge-http-temperature\node_modules\sync-request\index.js:31:11)
    at Object.HttpTemperature.getState (C:\Users\paul.obrien\AppData\Roaming\npm\node_modules\homebridge-http-temperature\index.js:41:17)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at Characteristic.getValue (C:\Users\paul.obrien\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Characteristic.js:120:10)
    at Bridge.<anonymous> (C:\Users\paul.obrien\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Accessory.js:621:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (C:\Users\paul.obrien\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Accessory.js:585:8)
    at emitMany (events.js:108:13)
    at HAPServer.emit (events.js:182:7)

**Comment by lucacri** [comment]
We should see if the HomeKit standard allows a return type of "unavailable " and return that in case of exceptions

**Comment by Luc-cos** [comment]
I get same problem .....

**Comment by paulobriennz** [comment]
could we just log error in console but not return anything so homebridge doesn't know any different and we don't throw a (fatal) error?  I tried messing around with the return to try and get as close to 'null' as I could but just don't have enough experience to know what I am really doing..

in this part of 
homebridge-http-temperature\node_modules\sync-request\index.js 

where it returns successful HttpResponse or throws the error (which crashes homebridge), can we somehow modify the throw new Error line to throw a non threatening HttpResponse of nothing?  I tried returning a fake 'nothing' HttpResponse but got tripped up on not passing back headers etc.  

I don't quite get how in other plugins, you just get a log of connection refused etc., timeout but in this plugin it throws a fatal error.  is it because of this sync-request dependency?  is there another way to do an httrRequest that doesn't crash homebridge on error?  or is the problem back in the http-temperature\index.js where the returned error get's handled?

  if (response.success) {
    return new HttpResponse(response.response.statusCode, response.response.headers, response.response.body, response.response.url);
  } else {
    **throw new Error(response.error.message || response.error || response);**

**Comment by paulobriennz** [comment]
OK, complete dirty hack but works for me and seems to stop crashing:

In 
homebridge-http-temperature\node_modules\sync-request\index.js 

change line 31 from:

throw new Error(response.error.message || response.error || response);
to
return;

In
homebridge-http-temperature\index.js
change this bit around line 42:

if(res.statusCode > 400){
    this.log('HTTP get state function failed');
    callback(error);

to
if(res == null){
    this.log('HTTP get state function failed');
    callback(null, 0);

It then just reports 0 temperature instead of Error = Crash.
It wont log a proper error but in my testing that doesn't really matter, id prefer a temp of 0 then the bridge crashing.

EDIT:  I found that if the temp sensor was giving a reading of 'nan' homebridge would also crash.
Think I've sussed with this mod in the getstate method:

getState: function (callback) {
      var body;
      var res = request(this.http_method, this.url, {});
      if(res == null){
         this.log('HTTP get state function failed');
         callback(null, 0);
      } else {
         this.log('HTTP get state function succeeded!');
         if (res.body.toString().indexOf("nan") > -1) 
         {
             this.log('Ignoring value: nan');
             callback(null, 0);
         }
         else
         {
              var info = JSON.parse(res.body);
             this.temperatureService.setCharacteristic(
                Characteristic.CurrentTemperature,
                info.temperature
             );
             this.log(info);
             this.temperature = info.temperature;
             callback(null, this.temperature);
         }  
        }
   },

**Comment by lucacri** [comment]
Do you want to submit a PR?

**Comment by PeterBrain** [comment]
i guess i have fixed the issue

try it and tell me what you think:
sudo npm install -g https://github.com/PeterBrain/homebridge-http-temperature-humidity

**Comment by jendaz** [comment]
I had the same issue if the ip address is not reachable. For example my thermometer is disconnected or unplugged. Is this solved in last version?
Have you pushed the fix to production version?

**Comment by jendaz** [comment]
@lucacri is the issue fixed with merge of pull request #29 ?

**Comment by lucacri** [comment]
I didn't try it (not using this module at the time), can anyone check version 0.0.16 and report back?

**Comment by jendaz** [comment]
The version from npm is not working correctly and is not containing last code from here. So actually I switched to https://www.npmjs.com/package/homebridge-advanced-http-temperature-humidity which is working also with disconnected thermometer or unreachable url endpoint.
