### ISSUE TITLE
0.0.8: SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by gretel** [lucacri/homebridge-http-temperature-humidity#4]
```
Feb 09 17:06:45 DietPi node[10375]: ERROR LOADING PLUGIN homebridge-http-temperature-humidity:
Feb 09 17:06:45 DietPi node[10375]: SyntaxError: missing ) after argument list
Feb 09 17:06:45 DietPi node[10375]: at exports.runInThisContext (vm.js:53:16)
Feb 09 17:06:45 DietPi node[10375]: at Module._compile (module.js:374:25)
Feb 09 17:06:45 DietPi node[10375]: at Object.Module._extensions..js (module.js:405:10)
Feb 09 17:06:45 DietPi node[10375]: at Module.load (module.js:344:32)
Feb 09 17:06:45 DietPi node[10375]: at Function.Module._load (module.js:301:12)
Feb 09 17:06:45 DietPi node[10375]: at Module.require (module.js:354:17)
Feb 09 17:06:45 DietPi node[10375]: at require (internal/module.js:12:17)
Feb 09 17:06:45 DietPi node[10375]: at Plugin.load (/opt/node/lib/node_modules/homebridge/lib/plugin.js:65:22)
Feb 09 17:06:45 DietPi node[10375]: at Server.<anonymous> (/opt/node/lib/node_modules/homebridge/lib/server.js:70:14)
Feb 09 17:06:45 DietPi node[10375]: at Array.forEach (native)
```

**Comment by lucacri** [comment]
Try using the latest version

**Comment by gretel** [comment]
i did, what's your point?

**Comment by lucacri** [comment]
The version 0.0.8 is very old (i was using them for testing), I pushed one last night and it should be good. Also, check/post here your config file, maybe something is missing
